# Generated by Django 4.2.30 on 2026-06-19 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moodle_user_id', models.IntegerField(blank=True, null=True)),
                ('moodle_course_id', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENROLLING', 'Enrolling'), ('ENROLLED', 'Enrolled'), ('FAILED', 'Failed'), ('UNENROLLED', 'Unenrolled')], default='PENDING', max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('unenrolled_at', models.DateTimeField(blank=True, null=True)),
                ('completion_status', models.JSONField(blank=True, null=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='applications.application')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
