# Generated by Django 4.2.13 on 2026-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='moodle_temp_password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
