# Generated by Django 4.2.13 on 2026-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_add_moodle_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='de_enrolment_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='de_enrolment_type',
            field=models.CharField(blank=True, choices=[('MANDATORY', 'Mandatory'), ('VOLUNTARY', 'Voluntary')], default='', max_length=10),
        ),
    ]
