# Generated by Django 4.2.13 on 2026-07-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseschedule_lecturer'),
        ('enrollments', '0003_add_de_enrolment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected course completion date', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='The specific intake/schedule the student is enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.courseschedule'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(blank=True, help_text='Course commencement date for this student', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
