# Generated by Django 4.2.13 on 2026-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('SUPERADMIN', 'Super Admin'), ('LECTURER', 'Lecturer'), ('CENTRE_ADMIN', 'Centre Administrator')], default='STUDENT', max_length=20),
        ),
    ]
