# Generated by Django 4.2.13 on 2026-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_lecturer_centreadmin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
