# Generated by Django 4.2.13 on 2026-07-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zntc_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
