# Generated by Django 4.2.13 on 2026-07-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_zntc_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ec_number',
            field=models.CharField(blank=True, default='', help_text='ZESA EC number for ZNTC staff (e.g. EC-12345)', max_length=20),
        ),
    ]
