# Generated by Django 4.2.13 on 2026-07-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_assigned_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hexco_level',
            field=models.CharField(blank=True, choices=[('NC', 'National Certificate (NC)'), ('ND', 'National Diploma (ND)')], default='', max_length=2),
        ),
    ]
