# Generated by Django 4.2.13 on 2026-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_add_hexco_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='guardian_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='hostel_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='is_resident',
            field=models.BooleanField(default=False, help_text='True if student will stay in ZNTC hostel'),
        ),
        migrations.AddField(
            model_name='application',
            name='responsible_party',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='student_category',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct Applicant'), ('APPRENTICE', 'Apprentice (Company-Sponsored)'), ('INTERNAL', 'Internal ZESA Staff')], default='', max_length=12),
        ),
    ]
