# Generated by Django 4.2.13 on 2026-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_category_guardian_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
