# Generated by Django 4.2.13 on 2026-07-02 13:29

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_ref_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='academic_certs_doc',
            field=models.FileField(blank=True, help_text='Academic certificates (PDF)', null=True, upload_to=apps.applications.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='application',
            name='national_id_doc',
            field=models.FileField(blank=True, help_text='National ID card or passport scan (PDF, JPG, PNG)', null=True, upload_to=apps.applications.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='application',
            name='student_photo',
            field=models.ImageField(blank=True, help_text='Passport-size photo (JPG, PNG)', null=True, upload_to=apps.applications.models.application_upload_path),
        ),
    ]
