# Generated by Django 4.2.13 on 2026-07-02 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_add_document_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('ONLINE', 'Online (Student Self-Service)'), ('WALK_IN', 'Walk-in (Staff Captured)')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='staff_captured_by',
            field=models.ForeignKey(blank=True, help_text='Set when source=WALK_IN; the staff member who entered this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
