# Generated by Django 4.2.13 on 2026-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_add_walkin_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
