# Generated by Django 4.2.13 on 2026-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_add_escalation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code_of_conduct_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='code_of_conduct_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
