# Generated by Django 4.2.13 on 2026-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_add_code_of_conduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('MORE_INFO_REQUESTED', 'More Info Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('ENROLLED', 'Enrolled'), ('DE_ENROLLED', 'De-enrolled'), ('CERTIFIED', 'Certified')], default='DRAFT', max_length=25),
        ),
    ]
