# Generated by Django 4.2.13 on 2026-07-23 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0010_add_de_enrolled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='lecturer_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='lecturer_signed_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='lecturer_signed_off_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='lecturer_signoff_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
