# Generated by Django 4.2.13 on 2026-07-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_application_lecturer_signed_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by_ec_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
