# Generated by Django 4.2.13 on 2026-07-08 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_duration_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('week_in_month', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')])),
                ('max_capacity', models.PositiveIntegerField(default=20, help_text='Override course default capacity for this specific intake')),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open — Accepting Applications'), ('FULL', 'Full'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OPEN', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
            ],
            options={
                'ordering': ['year', 'month', 'week_in_month'],
                'unique_together': {('course', 'year', 'month', 'week_in_month')},
            },
        ),
    ]
