# Generated by Django 4.2.13 on 2026-07-08 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_course_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, help_text='Company or organisation name (for corporate enquiries)', max_length=200)),
                ('enquiry_type', models.CharField(choices=[('GENERAL', 'General Information'), ('COURSE_INFO', 'Course Details & Requirements'), ('FEES', 'Fees & Payment'), ('ADMISSION', 'Admission & Application'), ('CORPORATE', 'Corporate / Group Booking')], default='GENERAL', max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Specific course the enquiry relates to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
