# Generated by Django 4.2.13 on 2026-07-23 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_add_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Lecturer responsible for this intake', limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
