# Generated by Django 4.2.30 on 2026-06-19 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('ENROLLMENT_SUMMARY', 'Enrollment Summary'), ('PAYMENT_SUMMARY', 'Payment Summary'), ('COMPLETION_RATES', 'Completion Rates'), ('DEPARTMENT_USAGE', 'Department Usage'), ('CERTIFICATE_ISSUANCE', 'Certificate Issuance')], max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
