# Generated by Django 4.2.30 on 2026-06-18 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_matched', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SAP Sync Log',
                'verbose_name_plural': 'SAP Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(choices=[('PAYNOW', 'Paynow'), ('SAP_BUDGET', 'SAP Budget Transfer'), ('MANUAL', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('paynow_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('paynow_poll_url', models.CharField(blank=True, max_length=500, null=True)),
                ('paynow_redirect_url', models.CharField(blank=True, max_length=500, null=True)),
                ('sap_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('raw_webhook_payload', models.JSONField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.application')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
