# Generated by Django 4.2.13 on 2026-07-22 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who manually confirmed this payment, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, default='', help_text='Bank reference, EcoCash transaction ID, or receipt number (manually confirmed payments).', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('PAYNOW', 'Paynow'), ('SAP_BUDGET', 'SAP Budget Transfer'), ('CASH', 'Cash'), ('EFT', 'EFT / Bank Transfer'), ('RTGS', 'RTGS'), ('ECOCASH', 'EcoCash'), ('ZIMSWITCH', 'ZimSwitch'), ('COMPANY', 'Company / Sponsor Payment')], max_length=20),
        ),
    ]
