'use client'

import { BarChart2, FileText } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { format } from 'date-fns'
import AdminLayout from '@/components/layout/AdminLayout'
import PageHeader from '@/components/ui/PageHeader'
import Card from '@/components/ui/Card'
import Spinner from '@/components/ui/Spinner'
import api from '@/lib/api'
import type { Report, PaginatedResponse } from '@/types'

function useReports() {
  return useQuery<PaginatedResponse<Report>>({
    queryKey: ['reports'],
    queryFn: async () => {
      const { data } = await api.get('/reports/')
      return data
    },
  })
}

const reportTypeLabel: Record<string, string> = {
  ENROLLMENT_SUMMARY:  'Enrollment Summary',
  APPLICATION_SUMMARY: 'Application Summary',
  COURSE_COMPLETION:   'Course Completion',
  FINANCIAL_SUMMARY:   'Financial Summary',
}

export default function AdminReportsPage() {
  const { data, isLoading } = useReports()
  const reports = data?.results ?? []

  return (
    <AdminLayout>
      <PageHeader
        title="Reports"
        subtitle="Generated training and enrollment reports."
      />

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4 mb-8">
        {Object.entries(reportTypeLabel).map(([type, label]) => {
          const count = reports.filter((r) => r.report_type === type).length
          return (
            <Card key={type} className="text-center">
              <BarChart2 className="h-6 w-6 text-primary mx-auto mb-2" />
              <p className="text-2xl font-bold text-primary">{count}</p>
              <p className="mt-1 text-xs text-gray-500">{label}</p>
            </Card>
          )
        })}
      </div>

      <Card header={<h2 className="font-semibold text-gray-900">Recent Reports</h2>}>
        {isLoading && (
          <div className="flex justify-center py-10">
            <Spinner className="text-primary" />
          </div>
        )}

        {!isLoading && reports.length === 0 && (
          <div className="flex flex-col items-center py-10 text-center">
            <FileText className="h-10 w-10 text-gray-300 mb-3" />
            <p className="text-sm text-gray-500">No reports have been generated yet.</p>
            <p className="text-xs text-gray-400 mt-1">
              Reports are generated automatically by scheduled tasks.
            </p>
          </div>
        )}

        {!isLoading && reports.length > 0 && (
          <div className="overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr className="border-b text-xs text-gray-500 uppercase tracking-wide">
                  <th className="pb-3 text-left font-medium">Title</th>
                  <th className="pb-3 text-left font-medium hidden sm:table-cell">Type</th>
                  <th className="pb-3 text-left font-medium hidden md:table-cell">Generated by</th>
                  <th className="pb-3 text-left font-medium">Date</th>
                  <th className="pb-3 text-left font-medium">Download</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {reports.map((report) => (
                  <tr key={report.id}>
                    <td className="py-3 font-medium text-gray-900">{report.title}</td>
                    <td className="py-3 text-gray-600 hidden sm:table-cell">
                      {reportTypeLabel[report.report_type] ?? report.report_type}
                    </td>
                    <td className="py-3 text-gray-600 hidden md:table-cell">{report.generated_by_name}</td>
                    <td className="py-3 text-gray-500">
                      {format(new Date(report.generated_at), 'dd MMM yyyy')}
                    </td>
                    <td className="py-3">
                      {report.file_url ? (
                        <a
                          href={report.file_url}
                          className="text-primary hover:underline text-xs"
                          target="_blank"
                          rel="noreferrer"
                        >
                          Download
                        </a>
                      ) : (
                        <span className="text-xs text-gray-400">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </AdminLayout>
  )
}
